--liquibase formatted sql

--changeset gbabiuc:create-AccountStatus-ENUM splitStatements:false
CREATE TYPE AccountStatus AS ENUM (
    'ACTIVE',
    'BLOCKED'
    );

--changeset gbabiuc:create-CardStatus-ENUM splitStatements:false
CREATE TYPE CardStatus AS ENUM (
    'ACTIVE',
    'BLOCKED'
    );

--changeset gbabiuc:create-TransactionType-ENUM splitStatements:false
CREATE TYPE TransactionType AS ENUM (
    'DEPOSIT',
    'WITHDRAW',
    'TRANSFER'
    );

--changeset gbabiuc:create-Currency-ENUM splitStatements:false
CREATE TYPE Currency AS ENUM (
    'USD',
    'EUR',
    'MDL'
    );

--changeset gbabiuc:create-LoansStatus-ENUM splitStatements:false
CREATE TYPE LoansStatus AS ENUM (
    'OPEN',
    'CLOSED'
    );

--changeset gbabiuc:create-Roles-ENUM splitStatements:false
CREATE TYPE Roles AS ENUM (
    'USER',
    'ADMIN'
    );

--changeset gbabiuc:create-clients-table splitStatements:false
CREATE TABLE clients
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    birthdate  DATE         NOT NULL,
    phone      VARCHAR(15)  NOT NULL,
    address    VARCHAR(255),
    user_id    BIGINT
);

--changeset gbabiuc:create-account_types-table splitStatements:false
CREATE TABLE account_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255)
);

--changeset gbabiuc:create-accounts-table splitStatements:false
CREATE TABLE accounts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number          VARCHAR(20) UNIQUE NOT NULL,
    client_id       BIGINT             NOT NULL,
    account_type_id BIGINT             NOT NULL,
    balance         DECIMAL(15, 2)     NOT NULL,
    currency        Currency           NOT NULL,
    created_at      DATE               NOT NULL,
    status          AccountStatus      NOT NULL
);

--changeset gbabiuc:create-cards-table splitStatements:false
CREATE TABLE cards
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT             NOT NULL,
    number          VARCHAR(16) UNIQUE NOT NULL,
    expiration_date DATE               NOT NULL,
    cvv             VARCHAR(3)         NOT NULL,
    pin             VARCHAR(4)         NOT NULL,
    status          CardStatus         NOT NULL,
    issue_date      DATE DEFAULT 'NOW()'
);

--changeset gbabiuc:create-transactions-table splitStatements:false
CREATE TABLE transactions
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_account_id      BIGINT,
    destination_account_id BIGINT         NOT NULL,
    transaction_type       TransactionType,
    amount                 DECIMAL(15, 2) NOT NULL,
    currency               Currency       NOT NULL,
    created_at             TIMESTAMP      NOT NULL DEFAULT 'NOW()',
    description            VARCHAR(255)
);

--changeset gbabiuc:create-loans-table splitStatements:false
CREATE TABLE loans
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT         NOT NULL,
    amount        DECIMAL(15, 2) NOT NULL,
    interest_rate DECIMAL(5, 2)  NOT NULL,
    date          DATE           NOT NULL,
    term_months   INT            NOT NULL,
    status        loansStatus    NOT NULL,
    currency      Currency       NOT NULL
);

--changeset gbabiuc:create-loan_payments-table splitStatements:false
CREATE TABLE loan_payments
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id  BIGINT         NOT NULL,
    amount   DECIMAL(15, 2) NOT NULL,
    date     DATE           NOT NULL,
    currency Currency       NOT NULL
);

--changeset gbabiuc:create-exchange_rates-table splitStatements:false
CREATE TABLE exchange_rates
(
    id              SERIAL PRIMARY KEY,
    base_currency   VARCHAR(3)     NOT NULL,
    target_currency VARCHAR(3)     NOT NULL,
    rate            DECIMAL(15, 6) NOT NULL,
    date            DATE           NOT NULL
);

--changeset gbabiuc:create-account_limits-table splitStatements:false
CREATE TABLE account_limits
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_type_id        BIGINT         NOT NULL,
    daily_withdrawal_limit DECIMAL(15, 2) NOT NULL,
    daily_transfer_limit   DECIMAL(15, 2) NOT NULL,
    monthly_transfer_limit DECIMAL(15, 2) NOT NULL,
    currency               Currency       NOT NULL
);

--changeset gbabiuc:create-users-table splitStatements:false
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50) UNIQUE  NOT NULL,
    password   VARCHAR(100)        NOT NULL,
    email      VARCHAR(255) UNIQUE NOT NULL,
    role       Roles               NOT NULL,
    created_at TIMESTAMP DEFAULT 'NOW()'
);

--changeset gbabiuc:add-accounts-foreign_key splitStatements:false
ALTER TABLE accounts
    ADD FOREIGN KEY (client_id) REFERENCES clients (id);

--changeset gbabiuc:add-transactions-foreign_key splitStatements:false
ALTER TABLE transactions
    ADD FOREIGN KEY (source_account_id) REFERENCES accounts (id);

--changeset gbabiuc:add-transactions1-foreign_key splitStatements:false
ALTER TABLE transactions
    ADD FOREIGN KEY (destination_account_id) REFERENCES accounts (id);

--changeset gbabiuc:add-loans-foreign_key splitStatements:false
ALTER TABLE loans
    ADD FOREIGN KEY (client_id) REFERENCES clients (id);

--changeset gbabiuc:add-loan_payments-foreign_key splitStatements:false
ALTER TABLE loan_payments
    ADD FOREIGN KEY (loan_id) REFERENCES loans (id);

--changeset gbabiuc:add-accounts1-foreign_key splitStatements:false
ALTER TABLE accounts
    ADD FOREIGN KEY (account_type_id) REFERENCES account_types (id);

--changeset gbabiuc:add-account_limits-foreign_key splitStatements:false
ALTER TABLE account_limits
    ADD FOREIGN KEY (account_type_id) REFERENCES account_types (id);

--changeset gbabiuc:add-cards-foreign_key splitStatements:false
ALTER TABLE cards
    ADD FOREIGN KEY (account_id) REFERENCES accounts (id);

--changeset gbabiuc:add-clients-foreign_key splitStatements:false
ALTER TABLE clients
    ADD FOREIGN KEY (user_id) REFERENCES users (id);
